gpu_program: gpu_program.cu lodepng.cu
	nvcc -o gpu_program gpu_program.cu -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64"
clean:
	rm -f *.o 